# Generated by Django 4.2.3 on 2023-08-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_brand_product_subcategory_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='maincategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Maincategory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
