# Generated by Django 4.2.3 on 2023-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='brands'),
        ),
    ]
