# Generated by Django 4.2.3 on 2023-09-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_brand_pic1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='pic1',
            new_name='pic',
        ),
    ]
