# Generated by Django 4.2.3 on 2023-09-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_rename_pic1_brand_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='pic',
        ),
    ]
