# Generated by Django 4.2.3 on 2023-09-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_remove_brand_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='brands'),
        ),
    ]
