# Generated by Django 4.2.3 on 2023-09-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
