# Generated by Django 4.2.3 on 2023-09-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_checkout_checkoutproducts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='subTotal',
            new_name='subtotal',
        ),
    ]
