# Generated by Django 4.2.3 on 2023-09-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_rename_subtotal_checkout_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutproducts',
            old_name='Checkout',
            new_name='checkout',
        ),
    ]
